# Generated by Django 4.2.25 on 2025-10-31 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_no', models.CharField(max_length=20, unique=True)),
                ('borrower_name', models.CharField(max_length=100)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
