# Generated by Django 4.2.25 on 2025-10-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Razorpay', 'Razorpay'), ('UPI', 'UPI')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
