# Generated by Django 4.2.25 on 2025-10-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_remove_payment_created_at_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
