# Generated by Django 6.0.1 on 2026-01-22 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_payment_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
