# Generated by Django 4.2.25 on 2025-10-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
