import React from 'react';
import { ScrollView, View, Text, Linking, StyleSheet } from 'react-native';

export default function Privacy() {
  return (
    <ScrollView style={{backgroundColor: '#cecbcbff'}}>
      {/* Top cut header */}
      <View style={styles.topCut}>
        <Text style={styles.heading}>Privacy Policy</Text>
        <Text style={styles.updated}>Last updated: October 16, 2025</Text>
        <Text style={styles.readDetails}>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </Text>
      </View>

      {/* Content */}
      <View style={styles.content}>
        <Text style={styles.sectionHeading}>Interpretation and Definitions</Text>
        <Text style={styles.subHeading}>Interpretation</Text>
        <Text style={styles.paragraph}>
          The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </Text>

        <Text style={styles.subHeading}>Definitions</Text>
        <Text style={styles.paragraph}>For the purposes of this Privacy Policy:</Text>

        <View style={styles.list}>
          <Text style={styles.listItem}><Text style={styles.bold}>Account</Text> means a unique account created for You to access our Service or parts of our Service.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Affiliate</Text> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Application</Text> refers to Z, the software program provided by the Company.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Company</Text> refers to Zolaism Networks Pvt Ltd, 11D Konneriryanthoppu Street, (Behind Bus Stand), Cheyyar - 604 407. Thiruvannamalai Dt, Tamil Nadu. INDIA.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Country</Text> refers to: Tamil Nadu, India.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Device</Text> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Personal Data</Text> is any information that relates to an identified or identifiable individual.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Service</Text> refers to the Application.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Service Provider</Text> means any natural or legal person who processes the data on behalf of the Company.</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
          <Text style={styles.listItem}><Text style={styles.bold}>You</Text> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
        </View>

        {/* Add additional sections like 'Collecting and Using Your Personal Data', 'Use of Your Personal Data', etc. here similarly */}
        {/* For brevity, example content shown below */}

        <Text style={styles.sectionHeading}>Collecting and Using Your Personal Data</Text>
        <Text style={styles.subHeading}>Types of Data Collected</Text>
        <Text style={styles.subSubHeading}>Personal Data</Text>
        <Text style={styles.paragraph}>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information...
        </Text>

        {/* Continue with your full privacy content structured similarly */}

        <Text style={styles.sectionHeading}>Contact Us</Text>
        <Text style={styles.paragraph}>If you have any questions about this Privacy Policy, You can contact us:</Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>By email: support@zolaism.co.in</Text>
          <Text
            style={[styles.listItem, styles.link]}
            onPress={() => Linking.openURL('http://www.zolaismnetworks.com/')}
          >
            By visiting this page on our website: http://www.zolaismnetworks.com/
          </Text>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  topCut: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 54,
    paddingBottom: 48,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 12,
  },
  heading: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#8B2323',
    marginBottom: 18,
  },
  updated: {
    fontSize: 15,
    color: '#8B2323',
    marginBottom: 8,
  },
  readDetails: {
    fontSize: 15,
    color: '#8B2323',
    textAlign: 'center',
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 30,
    backgroundColor: '#cecbcbff',
  },
  sectionHeading: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#8B2323',
    marginTop: 20,
    marginBottom: 10,
  },
  subHeading: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#8B2323',
    marginTop: 12,
    marginBottom: 8,
  },
  subSubHeading: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#8B2323',
    marginTop: 10,
    marginBottom: 6,
  },
  paragraph: {
    fontSize: 15,
    color: '#333',
    marginBottom: 14,
  },
  list: {
    paddingLeft: 14,
  },
  listItem: {
    fontSize: 15,
    color: '#4b4b4b',
    marginBottom: 8,
  },
  bold: {
    fontWeight: 'bold',
    color: '#8B2323',
  },
  link: {
    color: '#007bff',
    textDecorationLine: 'underline',
  },
});
