/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Help`; params?: Router.UnknownInputParams; } | { pathname: `/Histroy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/invoice`; params?: Router.UnknownInputParams; } | { pathname: `/LoanDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Terms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/component/backbutton`; params?: Router.UnknownInputParams; } | { pathname: `/loan/[loan_no]`, params: Router.UnknownInputParams & { loan_no: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Help`; params?: Router.UnknownOutputParams; } | { pathname: `/Histroy`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/invoice`; params?: Router.UnknownOutputParams; } | { pathname: `/LoanDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Terms`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/component/backbutton`; params?: Router.UnknownOutputParams; } | { pathname: `/loan/[loan_no]`, params: Router.UnknownOutputParams & { loan_no: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Help${`?${string}` | `#${string}` | ''}` | `/Histroy${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/invoice${`?${string}` | `#${string}` | ''}` | `/LoanDetails${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/Privacy${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/Terms${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/component/backbutton${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Help`; params?: Router.UnknownInputParams; } | { pathname: `/Histroy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/invoice`; params?: Router.UnknownInputParams; } | { pathname: `/LoanDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Terms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/component/backbutton`; params?: Router.UnknownInputParams; } | `/loan/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/loan/[loan_no]`, params: Router.UnknownInputParams & { loan_no: string | number; } };
    }
  }
}
